POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "bad_password",
  "fullName": "Test Test"
}

###

POST http://localhost:3000/api/auth/login